### ISSUE TITLE
Fallas en Chrome iOS

### ISSUE THREAD

**Issue by guillemontecinos** [comandogabrielboric/Boric_Presidente#11]
* Landing Page no está cargando las imágenes en version móvil
* iOS 13.4
* Chrome V93.0.4577.78

![0747604D-3873-42F9-A177-382BAECF271C](https://user-images.githubusercontent.com/19594257/145695999-58439873-68d0-43aa-9c46-3b28553aa171.PNG)

**Comment by comandogabrielboric** [comment]
Corregido
