### ISSUE TITLE
Usar archivo estático o embed de Nextcloud en vez de Google Drive para el programa de gobierno.

### ISSUE THREAD

**Issue by wiredsis** [comandogabrielboric/Boric_Presidente#2]
Aunque Google Drive no sea una mala opción, lamentablemente incluye cookies externas que pueden potencialmente ser usadas para tracking. Recomendaría usar un iframe hacia un archivo en la página web misma o en Nextcloud a el PDF, ya que la mayoría de navegadores modernos tienen soporte para mostrar PDFs en un lector incluido.

**Comment by comandogabrielboric** [comment]
Muchas gracias por tu aporte, tomamos la decision de utilizar el iframe de google drive por la facilidad de visualizacion en dispositivos moviles. de todas maneras realizaremos las pruebas necesarias para mejorar :D
