### ISSUE TITLE
Actívate

### ISSUE THREAD

**Issue by agucova** [comandogabrielboric/Boric_Presidente#5]
@Monalmo @camonunez Hay algunos errores en el sitio de Actívate y me encantaría aportar, pero veo que no está incluido en este repo (además de no estar al día como se menciona en #3).

Aprovecho de preguntar si han intentado reconciliar cambios para el PR #1, dado que los problemas de accesibilidad siguen presentes en el sitio.

**Edit:** Actívate parece estar manejado por [un CMS](https://www.strikingly.com/), así que eso parece explicar su ausencia acá.

**Comment by agucova** [comment]
Hay hartas personas en Twitter y en comandos de RM que les gustaría aportar en temas digitales (hay hartes ingenieres). Si tienen una idea de cómo sumarnos, por favor dígannos!

**Comment by comandogabrielboric** [comment]
Hola Agustin, ya hemos integrado las mejoras de accesibilidad, veremos como pueden contribuir de manera mas directa con la campaña.

Saludos
